name: Deploy to Firebase Hosting on merge

on:
push:
branches:
- main

jobs:
build_and_deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v4

```
  - name: Set up Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '20'

  - name: Install dependencies
    run: npm ci || npm install

  - name: Build project
    run: npm run build

  - name: Verify build output
    run: ls -la build || echo "⚠️ Build folder not found."

  - name: Check for build directory
    run: |
      if [ ! -d "build" ]; then
        echo "❌ Build directory not found. Did the build fail?"
        exit 1
      fi

  - name: Deploy to Firebase Hosting
    uses: FirebaseExtended/action-hosting-deploy@v0
    with:
      repoToken: ${{ secrets.GITHUB_TOKEN }}
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_DEMO_DEPLOYMENT_PROJECT_ID }}
      channelId: live
      projectId: my-demo-deployment-project-id
```
